language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.2
      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: xenial
    - python: 3.5
      dist: xenial
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial

install:
    - pip install -r dev-requirements.txt
    - python setup.py install

script: nosetests
